### PR TITLE
drop python2 support, six

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by a-detiste** [comment]
ping

**Comment by pgajdos** [comment]
Please consider to accept this PR.

**Comment by a-detiste** [comment]
funcsigs should go too...

**Comment by rubik** [comment]
@a-detiste Apologies for the delay. Thank you for your contribution.

**Comment by a-detiste** [comment]
Thank you very much. It will take years to remove stray six usage, even in codebases that are not even Python2 compatible anymore.


In comparaison python3-funcsigs was removed pretty fast from Debian, like a two weeks job.

I will provide a second PR, or you can apply this patch (it was needed as a workaround in the bug in the release tooling, not even in Mando itself,  but as it was the last user of funcsigs it was the most practical thing to do):

https://salsa.debian.org/python-team/packages/mando/-/commit/8b6db4beedf6cab73a0d7d995f12cf41d387c6d3

**Comment by rubik** [comment]
Thank you Alexandre! I'll apply that patch and release another minor version.

**Pull request merged**
